

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;


public partial class SuburbIncomeTable
{

    public string SuburbName { get; set; }

    public Nullable<int> NilIncomeCount { get; set; }

    public Nullable<int> TotalCount { get; set; }

}

